DROP TABLE IF EXISTS INVENTORY;

CREATE TABLE INVENTORY (
  id SERIAL PRIMARY KEY,
  item_name VARCHAR(250) NOT NULL,
  price NUMERIC NOT NULL,
  fk_seller_id NUMERIC REFERENCES SELLER(id)
);

CREATE TYPE GENDER as ENUM('L', 'P');

DROP TABLE IF EXISTS SELLER;
CREATE TABLE SELLER (
	id SERIAL PRIMARY KEY,
	email VARCHAR(50) NOT NULL,
	password VARCHAR NOT NULL,
	username VARCHAR(50) NOT NULL,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	avatar BYTEA,
	birth_date DATE NOT NULL,
	gender GENDER NOT NULL,
	vendor_type INTEGER NOT NULL
);

DROP TABLE IF EXISTS PHOTO_INVENTORY
CREATE TABLE PHOTO_INVENTORY(
    id SERIAL PRIMARY KEY,
    path VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    fk_inventory_id NUMERIC REFERENCES INVENTORY(id)
);

DROP TABLE IF EXISTS PHOTO_PROFILE;
CREATE TABLE PHOTO_PROFILE(
    id SERIAL PRIMARY KEY,
    path VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    fk_seller_id NUMERIC REFERENCES SELLER(id)
)

CREATE TABLE public.role
(
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL
);