CREATE TYPE GENDER as ENUM('L', 'P');

DROP TABLE IF EXISTS SELLER;
CREATE TABLE SELLER (
	id SERIAL PRIMARY KEY,
	email VARCHAR(50) NOT NULL,
	password VARCHAR NOT NULL,
	username VARCHAR(50) NOT NULL,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	avatar VARCHAR(200),
	birth_date DATE NOT NULL,
	gender VARCHAR(1) NOT NULL,
	vendor_type INTEGER NOT NULL,
	is_activated boolean NOT NULL,
	verification_code VARCHAR(64)
);

DROP TABLE IF EXISTS INVENTORY;
CREATE TABLE INVENTORY (
  id SERIAL PRIMARY KEY,
  item_name VARCHAR(250) NOT NULL,
  price NUMERIC NOT NULL,
  fk_seller_id int REFERENCES SELLER(id)
);

DROP TABLE IF EXISTS PHOTO_INVENTORY
CREATE TABLE PHOTO_INVENTORY(
    id SERIAL PRIMARY KEY,
    path VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    fk_inventory_id int REFERENCES INVENTORY(id)
);

DROP TABLE IF EXISTS PHOTO_PROFILE;
CREATE TABLE PHOTO_PROFILE(
    id SERIAL PRIMARY KEY,
    path VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    fk_seller_id int REFERENCES SELLER(id)
)

DROP TABLE IF EXISTS ROLE;
CREATE TABLE ROLE
(
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL
);

DROP TABLE IF EXISTS JWT_USER;
CREATE TABLE JWT_USER
(
    id SERIAL PRIMARY KEY NOT NULL,
    user_id SERIAL PRIMARY KEY NOT NULL,
    device_id VARCHAR NOT NULL,
    jwt VARCHAR NOT NULL,
    is_invalidated boolean NOT NULL
);

DROP TABLE IF EXISTS JWT_USER;
CREATE TABLE JWT_USER
(
    id SERIAL PRIMARY KEY NOT NULL,
    user_id SERIAL NOT NULL,
    device_id VARCHAR NOT NULL,
    jwt VARCHAR NOT NULL,
    is_invalidated boolean NOT NULL
);