DROP TABLE IF EXISTS INVENTORY;

CREATE TABLE INVENTORY (
  id SERIAL PRIMARY KEY,
  item_name VARCHAR(250) NOT NULL,
  price NUMERIC NOT NULL
);

CREATE TYPE GENDER as ENUM('L', 'P');

CREATE TABLE SELLER (
	id SERIAL PRIMARY KEY,
	email VARCHAR(50) NOT NULL,
	password VARCHAR NOT NULL,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	avatar BYTEA,
	birth_date DATE NOT NULL,
	gender GENDER NOT NULL,
	vendor_type INTEGER NOT NULL
);